### ISSUE TITLE
External Variables do not appear to work

### ISSUE THREAD

**Issue by adam-boosted** [microsoft/Power-CAT-Copilot-Studio-Kit#43]
I've followed along with the documentation for setting external variables.

https://learn.microsoft.com/en-us/microsoft-copilot-studio/guidance/pass-context-variables-from-webpage-to-copilot

I have tried a very simple example to pass in the global variable UserName as a string.

Here's the code for my conversational start topic:

```
kind: AdaptiveDialog
beginDialog:
  kind: OnConversationStart
  id: main
  actions:
    - kind: Question
      id: question_eQrwwA
      interruptionPolicy:
        allowInterruption: true

      variable: Global.UserName
      prompt:
      entity: StringPrebuiltEntity

    - kind: SendActivity
      id: sendMessage_M0LuhV
      activity:
        text:
          - |-
            Hello! 👋 I'm your Virtual Assistant. How can I assist you today?
            Enter your question to get started. 😊
        speak:
          - Thanks for calling, how can I help?
```

Here's the code for my greeting topic:

```
kind: AdaptiveDialog
beginDialog:
  kind: OnRecognizedIntent
  id: main
  intent:
    displayName: Greeting
    includeInOnSelectIntent: false
    triggerQueries:
      - Good afternoon
      - Good morning
      - Hello
      - Hey
      - Hi

  actions:
    - kind: SendActivity
      id: sendMessage_abmysR
      activity:
        text:
          - |
            Hello, how can I help you today {Global.UserName}?
        speak:
          - Hello, <break strength="medium" /> how can I help?

    - kind: CancelAllDialogs
      id: cancelAllDialogs_01At22
```

You can see in the screenshot that `Global.UserName` is configured to allow external sources to set it:

<img width="341" alt="image" src="https://github.com/user-attachments/assets/08a329a7-6257-485b-b1b6-0e27afe28da0">

When I am running this testing solution, I have a very simple test that looks like this:

<img width="1274" alt="image" src="https://github.com/user-attachments/assets/cd0950b2-e883-4ac3-ba60-56edb1e61b99">

This is what the test result is, for the utterance "Hello"

<img width="1276" alt="Screenshot 2024-09-04 at 1 48 16 PM" src="https://github.com/user-attachments/assets/38b9e339-a5f2-480a-860e-622b54604df9">

The utterance is being assigned to `Global.UserName` for some reason.

Am I using External Variables JSON incorrectly? How should I be using it?
